name: Publish

on: [push]

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.MIGITHUB_TOKEN }}
        file: carlosbrc.pdf
        asset_name: carlosbrc.pdf
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"